version: '3.1'

volumes:
  prometheus_data:
  grafana_data:
services:
  mongo:
    image: mongo
    container_name: "ticketing_mongodb"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ticketing-service
    volumes:
      - ./scripts/docker:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    hostname: mongo
  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
  prometheus:
    image: prom/prometheus
    container_name: "prometheus"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000