version: '3.1'

services:
  mongo:
    image: mongo
    container_name: "ticketing_mongodb"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ticketing-service
    volumes:
      - ./scripts/docker:/docker-entrypoint-initdb.d
    hostname: mongo
    expose:
      - 27017
    ports:
      - "27017:27017"

  spring:
    build:
      dockerfile: ticket-service/Dockerfile
    container_name: "ticketing_spring"
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
    ports:
      - "8080:8080"