version: '3.1'

services:
  mongo:
    image: mongo
    container_name: "ticketing_mongodb"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ticketing-service
    volumes:
      - ./scripts/docker:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"