spring:
  rabbitmq:
    addresses: ${amqpURL:amqp://guest:guest@localhost}
server:
  port: 8081
broker:
  queue:
    ticket:
      name: default.ticket

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    hostname: "localhost"