spring:
    application:
        name: "ticket-ms"
    data:
        mongodb:
            authentication-database: admin
            database: ticketing-service
            host: ${MONGO_HOST:localhost}
            password: password
            port: 27017
            username: root
    rabbitmq:
        addresses: ${amqpURL:amqp://guest:guest@localhost}
broker:
    queues:
        ticket:
            name: default.ticket
    exchanges:
        ticket:
            name: direct.ticket
            type: direct
    bindings:
        ticket:
            exchange: direct.ticket
            queue: default.ticket
            routingKey: default.ticket

springdoc:
    swagger-ui:
        path: /docs/swagger.html

management:
    endpoints:
        enabled-by-default: false
        web:
            exposure:
                include: 'health,prometheus'
    endpoint:
        health:
            enabled: true
            show-details: always
        prometheus:
            enabled: true

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        hostname: "localhost"