spring:
    data:
        mongodb:
            authentication-database: admin
            database: ticketing-service
            host: ${MONGO_HOST:localhost}
            password: password
            port: 27017
            username: root
    rabbitmq:
        addresses: ${amqpURL:amqp://guest:guest@localhost}
broker:
    queues:
        ticket:
            name: default.ticket
    exchanges:
        ticket:
            name: direct.ticket
            type: direct
    bindings:
        ticket:
            exchange: direct.ticket
            queue: default.ticket
            routingKey: default.ticket

springdoc:
    swagger-ui:
        path: /docs/swagger.html
