spring:
    data:
        mongodb:
            authentication-database: admin
            database: ticketing-service
            host: ${MONGO_HOST:localhost}
            password: password
            port: 27017
            username: root
    rabbitmq:
        adresses: ${amqpURL:todo}
broker:
    queue:
        ticket:
            name: default.ticket
springdoc:
    swagger-ui:
        path: /docs/swagger.html
